version: '3'
services:
  todos_app:
    container_name: todos_container
    build: .
    image: horia22/todos-nodejs
    ports: 
      - "4000:4000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 10s 

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /.docker/config.json:/config.json
    command: --interval 30 --cleanup todos_container
    environment:
      - WATCHTOWER_DOCKER_CONFIG=/config.json
      - WATCHTOWER_POLL_INTERVAL=30
      - WATCHTOWER_CLEANUP=true
    restart: unless-stopped
