version: '3'
services:
   todos_app:
    container_name: todos_container
    build: .
    image: horia22/todos-nodejs
    ports: 
      - "4000:4000"
    env_file:
      - .env 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

