apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-deployment
  namespace: default
  labels:
    app: todos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos
  template:
    metadata:
      labels:
        app: todos
    spec:
      containers:
        - name: todos
          image: horia22/todos-nodejs:latest
          ports:
            - containerPort: 4000
          env:
            - name: mongoDbUrl
              value: "mongodb+srv://horia:55EhCf40R0LhxnkW@devops.0ncrdau.mongodb.net/Todos_DB?retryWrites=true&w=majority"
      imagePullSecrets:
        - name: regcred
