apiVersion: v1
kind: Service
metadata:
  name: todos-service
  namespace: default
spec:
  selector:
    app: todos
  type: NodePort
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30761
