- name: Configure and Install Docker on Cloud VM
  hosts: cloud-servers
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: true
        state: started

- name: Configure and Install Docker on Oracle VM (CentOS)
  hosts: oracle-vm
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: true
        state: started
